language: python
python:
  - "2.7"
before_install:
  - wget -nc http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p conda
  - source conda/bin/activate root
  - conda update --yes -q conda
  - conda install --yes -c https://conda.binstar.org/rdkit rdkit nose coverage setuptools pip
install:
  - pip install -r requirements.txt
script:
  - nosetests --cover-package=sygma --with-coverage --cover-erase --cover-branches
after_script:
  - pip install codacy_coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml



